apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: circleci-runner-docker
  description: https://github.com/CircleCI-Public/circleci-runner-docker/blob/onprem-45/README.md
  annotations:
    circleci.com/project-slug: github/CircleCI-Public/circleci-runner-docker
    jira/project-key: ON-PREM
    pagerduty.com/service-id: PM7SMHG
  links:
    - url: "slack://channel?team=S01FY3NF31V&id=CAT9Q7TGW"
      title: Server Slack channel
      icon: chat
    - url: "https://github.com/CircleCI-Public/circleci-runner-docker/blob/main/README.md"
      title: Documentation
      icon: docs
  tags:
    - runner
    - onprem
    - docker
spec:
  type: service
  lifecycle: production
  owner: on-prem
