version: 2.1

parameters:
  agent_version:
    type: string
    description: version of launch-agent to build into Docker image (e.g. 1.0.16645-31711f7); use latest if not specified
    default: ""

workflows:
  dummy:
    jobs:
      - launch-agent-test
jobs:
  launch-agent-test:
    docker:
      - image: cimg/base:current
    steps:
      - run: "echo preparing repo for archiving"

